name: Backend Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create frontend dummy env
        run: touch ./frontend/.env
      - name: Set up backend config
        run: mv ./backend/.env.test ./backend/.env
      - name: Build Docker image
        run: |
          source .env.docker-compose
          docker compose build backend
      - name: Start services
        run: |
          source .env.docker-compose
          docker compose up --detach db storage
          docker ps
      - name: Run tests
        run: |
          source .env.docker-compose
          docker compose run -e CI=1 backend scripts/test.sh
      - name: Clean up
        if: always()
        run: |
          source .env.docker-compose
          docker compose down db storage --volumes
